# -*- coding: utf-8 -*-

from rich.console import Console

CONSOLE = Console()


class EXIT_CODE:
    MESHPROJECT_FILE_NOT_FOUND = 2
    COMPONENT_WITH_SYMBOL_EXISTS = 345
    MESHPROJECT_INVALID_FIELD_VALUE = 347
    MESHPROJECT_FILE_INVALID_YAML_SYNTAX = 348
    FILE_EXISTS = 349
